// PlanData.ts
export const PLAN_DATA = {
    monthly: [
        {
            title: "포켓 프롬프트 Free",
            price: "₩0",
            period: "월",
            features: [
                "Private 프롬프트 최대 5개",
                "저장한 프롬프트 최대 5개",
                "기본 모델 월 100회 사용",
            ],
            buttonLabel: "시작하기",
            planType: "free",
        },
        {
            title: "포켓 프롬프트 Lite",
            price: "₩9,900",
            period: "월",
            features: [
                "Private 프롬프트 최대 10개",
                "저장한 프롬프트 최대 10개",
                "기본 모델 무제한 사용",
                "고급 모델 월 100회 사용",
                "광고 없는 쾌적한 환경",
            ],
            buttonLabel: "구독하기",
            planType: "lite",
        },
        {
            title: "포켓 프롬프트 Standard",
            price: "₩29,900",
            period: "월",
            features: [
                "Private 프롬프트 최대 30개",
                "저장한 프롬프트 최대 30개",
                "기본 모델 무제한 사용",
                "고급 모델 월 300회 사용",
                "광고 없는 쾌적한 환경",
            ],
            buttonLabel: "구독하기",
            planType: "plus",
        },
        {
            title: "포켓 프롬프트 Pro",
            price: "₩49,900",
            period: "월",
            features: [
                "Private 프롬프트 최대 80개",
                "저장한 프롬프트 최대 80개",
                "기본 모델 무제한 사용",
                "고급 모델 월 500회 사용",
                "광고 없는 쾌적한 환경",
            ],
            buttonLabel: "구독하기",
            planType: "pro",
        },
    ],
    annual: [
        {
            title: "포켓 프롬프트 Free",
            price: "₩0",
            period: "년",
            features: [
                "Private 프롬프트 최대 5개",
                "저장한 프롬프트 최대 5개",
                "기본 모델 월 100회 사용",
            ],
            buttonLabel: "시작하기",
            planType: "free",
        },
        {
            title: "포켓 프롬프트 Lite",
            price: "₩99,000",
            period: "년",
            features: [
                "Private 프롬프트 최대 10개",
                "저장한 프롬프트 최대 10개",
                "기본 모델 무제한 사용",
                "고급 모델 월 100회 사용",
                "광고 없는 쾌적한 환경",
            ],
            buttonLabel: "구독하기",
            planType: "lite",
        },
        {
            title: "포켓 프롬프트 Standard",
            price: "₩299,000",
            period: "년",
            features: [
                "Private 프롬프트 최대 30개",
                "저장한 프롬프트 최대 30개",
                "기본 모델 무제한 사용",
                "고급 모델 월 300회 사용",
                "광고 없는 쾌적한 환경",
            ],
            buttonLabel: "구독하기",
            planType: "plus",
        },
        {
            title: "포켓 프롬프트 Pro",
            price: "₩499,000",
            period: "년",
            features: [
                "Private 프롬프트 최대 80개",
                "저장한 프롬프트 최대 80개",
                "기본 모델 무제한 사용",
                "고급 모델 월 500회 사용",
                "광고 없는 쾌적한 환경",
            ],
            buttonLabel: "구독하기",
            planType: "pro",
        },
    ],
};
