name: Amplify Preview Deployment

on:
    pull_request:
        branches:
            - develop
            - main
        types: [opened, synchronize, reopened]

permissions:
    issues: write
    pull-requests: write

jobs:
    preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Trigger Amplify Deployment
              run: |
                  aws amplify start-deployment \
                    --app-id d2ggjieg648h6b \
                    --branch-name ${{ github.head_ref }} \
                    --region us-east-1
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Set Environment Variables
              run: |
                  echo "LATEST_COMMIT=${{ github.sha }}" >> $GITHUB_ENV
                  echo "DEPLOY_LOG_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
                  echo "DEPLOY_PREVIEW_URL=https://develop.d2ggjieg648h6b.amplifyapp.com" >> $GITHUB_ENV
                  echo "ENVIRONMENT=preview" >> $GITHUB_ENV

            - name: Comment on PR
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  message: >
                      ### 🚀 Amplify Preview Success!
                      | Name                  | Link                                                                 |
                      |-----------------------|----------------------------------------------------------------------|
                      | **Latest Commit**     | [${{ env.LATEST_COMMIT }}](https://github.com/${{ github.repository }}/commit/${{ env.LATEST_COMMIT }}) |
                      | **Latest Deploy Log** | [View Logs](${{ env.DEPLOY_LOG_URL }})                          |
                      | **Deploy Preview URL**| [Preview Environment](${{ env.DEPLOY_PREVIEW_URL }})            |
                      | **Environment**       | ${{ env.ENVIRONMENT }}                                          |
