name: Vercel Preview Deployment

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        branches: [main, develop]
    workflow_dispatch:

permissions:
    contents: read
    deployments: write
    id-token: write
    pull-requests: write

jobs:
    Deploy:
        runs-on: ubuntu-latest
        env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.ACTION_TOKEN }}

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Build
              run: |
                  yarn build

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v20
              id: vercel
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

            - name: Comment PR
              uses: mshick/add-pr-comment@v2
              with:
                  message-id: vercel-preview
                  message: |
                      ### 👀 Preview Success!

                      |  Name | Link |
                      |---------------------------------|------------------------|
                      |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
                      |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
                      |<span aria-hidden="true">🖇️</span> Deploy Preview Url | [${{ steps.vercel.outputs.preview-url }}](${{ steps.vercel.outputs.preview-url }}) |
                      |<span aria-hidden="true">🌳</span> Environment | ${{ steps.vercel.outputs.environment }} |
