name: Amplify Preview Deployment

on:
    pull_request:
        branches:
            - develop
            - main
        types: [opened, synchronize, reopened]

permissions:
    issues: write
    pull-requests: write

jobs:
    preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get Amplify Preview URL
              run: |
                  BASE_URL="https://develop.d2ggjieg648h6b.amplifyapp.com"
                  echo "AMPLIFY_URL=${BASE_URL}" >> $GITHUB_ENV

            - name: Comment on PR
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { owner, repo, number } = context.issue;
                      const commentBody = `
🚀 Amplify Preview Success!

- **Latest Commit**: [${process.env.LATEST_COMMIT}](https://github.com/${owner}/${repo}/commit/${process.env.LATEST_COMMIT})
- **Latest Deploy Log**: [View Logs](${process.env.DEPLOY_LOG_URL})
- **Deploy Preview URL**: [Preview Environment](${process.env.DEPLOY_PREVIEW_URL})
- **Environment**: ${process.env.ENVIRONMENT}
            `;
                      github.rest.issues.createComment({
                        owner,
                        repo,
                        issue_number: number,
                        body: commentBody
                      });
