name: Amplify Preview Deployment

on:
    pull_request:
        branches:
            - develop
            - main
        types: [opened, synchronize, reopened]

jobs:
    preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get Amplify Preview URL
              run: |
                  BASE_URL="https://develop.d2ggjieg648h6b.amplifyapp.com"
                  echo "AMPLIFY_URL=${BASE_URL}" >> $GITHUB_ENV

            - name: Comment on PR
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { owner, repo, number } = context.issue;
                      const commentBody = `🚀 **Amplify Preview URL:** [개발환경 미리보기](${process.env.AMPLIFY_URL})`;
                      github.rest.issues.createComment({
                        owner,
                        repo,
                        issue_number: number,
                        body: commentBody
                      });
